css/styles.css, index.html
This pull request is regarding issue #9 
I have updated the hover effect on both the Download buttons.
Before -
After -
Kindly approve and merge the request.
Thankyou.
=> Hover effect updated

css/styles.css
Browser provide us with a white and grey color scroll bar in the right side of the screen. The default scroll was not matching with the Color Theme of you website, so I customized the scroll bar and now it looks like this:
=> Modified Default Scorll Bar

.vscode/settings.json, css/styles.css
This is regarding issue #6. Improved the testimonial section. Modified the font-size to enhance its appearance in small devices.
Approve and merge this to main file. Thank You!!
=> Improved the Testimonial section

css/styles.css, index.html
I have improved the navbar by making it bolder, improved its font size, and color
=> Enhanced Navbar

index.html
Fixed Overlapping of download button and Iphone Image.
Before:
After:
=> Fixed Overlapping

.github/workflows/greetings.yml, css/styles.css
**Description:**
This Pull Request addresses and resolves the issue related to the improper display of the Card component on mobile devices. The issue description can be found [here](https://github.com/marshadkhn/TinDog/issues/4).
**Changes Made:**
- Added shadow, border, and transition effects to enhance the Card's visual appeal.
- Responsive cards according to mobile,tablet,laptop,large display
- Made cards more fluid by adjusting their height and image size to adapt to various screen sizes.
- Implemented an enlarge effect on hover for a better user experience.
**Screenshots:**
Here's a screenshot showing the improvements made in this PR:
**Testing:**
I have thoroughly tested these changes on various mobile devices and emulators to ensure responsive behavior and compatibility.
**Related …
=> Mobile Card Alignment issue fixed

index.html
issue_no #39 
**Before**
**After Changes **
=> Login element issue fixed #39

css/styles.css, index.html
This PR is regarding issue #31 
I have updated the UI of adoption page as mentioned in the issue.
Kindly approve and merge the Pull Request.
Thankyou.
=> Adoption UI Updated

css/styles.css, index.html
https://github.com/marshadkhn/TinDog/assets/139707943/8d281973-64a6-4043-a0f4-7bf3733d1c89
=> Added hover effect in footer section with colors of social media platforms

css/forgot-password.css, forgot-password.html, login.html
=> Completed Forgot Password page

css/styles.css, index.html
This PR adds the Contact Us page in the website which can be accessed and visited  by navigation links.
Earlier there was no contact us page there in the website.
Fixes #22
=> Added contact us page to the website which can be visited via navbar links

index.html
I included the website link alongside the social media icons, using a new icon.
issue #32
=> website logo updated

css/styles.css, index.html, script.js
Issue: #46 
- I added a theme toggle button to the navbar.
- By toggling the button, it changes the theme of the whole website.
=> feat: added dark theme

css/styles.css
fixes #59 
***`before`*** <br>
***`after`*** <br>
=> Fix: title-image position

css/styles.css
=> updated the colour scheme of the submit button

css/styles.css
now the section looks like the following screenShot
=> hero section bg bug corrected

.vscode/settings.json, index.html
=> Twitter icon updated in home page

css/styles.css, index.html
=> Changed the login link into btn style

css/styles.css, index.html
When updating an icon or making changes to styles, it's common to adjust the associated CSS styles to ensure proper alignment, and positioning, or to maintain a cohesive design
=> UPDATED: #72<twitter_icon_updated>

.vscode/settings.json, css/forgot-password.css, css/login_style.css, css/signup_styles.css, forgot-password.html, login.html, signup.html
=> Created Navbar in login.html, signup.html & forgot-password.html

css/styles.css
** `The display and float property for submission button adjusted `**
fixes : #78
=> Display property and float property of submit btn adjusted

css/loginSignup.css
Before:
[Screencast from 04-10-23 05:55:03 PM IST.webm](https://github.com/marshadkhn/TinDog/assets/126847168/817ec1e7-c1fa-4033-9466-b0467bf8d952)
After:
[Screencast from 04-10-23 06:00:54 PM IST.webm](https://github.com/marshadkhn/TinDog/assets/126847168/adab2687-dee6-42cd-91cd-361ab91ae558)
=> changed the cursor style to pointer in signIn and signup btn

index.html
Error in the sentence in the pricing section of index.html.
I believe it should :
"Simple and affordable price plans for your dog."
I've attached a screenshot for your reference.
=> Feat: #83 <Error_in_Pricing_Section_Sentence>

.gitignore, css/styles.css, index.html
changes made with contact page send message button make it more user friendly with CSS glowing button hover effect.
=> button changes added

index.html
This pr fix- #107 
Updated the github link.
@marshadkhn Please mention all other social platform links.
=> [Fix}Updated github link

TinDog-main/css/styles.css, css/styles.css, index.html
Added box-shadow and scale effect on cards on hovering
=> Added hover effect on cards

index.html, mainCss/styles.css
I have given margin to slider button in testimonials, and also to images in the press section.
issue #118
=> Update testimonials and press

mainCss/styles.css
I have added hover effect on download button for apple.
Issue - #120
=> Added hover effect on button

css/styles.css, index.html, script/script.js
=> Enhancing landing page UI

css/styles.css, index.html, script/script.js
=> Revert "Enhancing landing page UI"

css/loginSignup.css, loginSignUp.script.js, loginSignup.html
fixes #129  
I have added a whole new loginSignUp page, with a better UI and more resonsive one.
=> [ADDED] : LoginSignUp Page 

html/chihuahua.html, info1.html
=> Text edited

css/style2.css, index.html
There were two download button. I removed the one. And update the with other new item such as Nutrition and Foods and Pets Toys And Product.
**previous:**
**current:**
**issue**: #131
=> Double Download Button
